config/routes.rb
Goblog::Application.routes.draw do
  # Root path
  root 'posts#index'

  get 'register', to: 'users#new'
  get 'logout',   to: 'sessions#destroy'
  get 'users/edit', to: 'users#edit'
  # Resources
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :posts
  resources :comments, only: [:create]
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Category < ActiveRecord::Base
  # Associations
  # has_many :posts
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  post_id    :integer
#  content    :text
#  created_at :datetime
#  updated_at :datetime
#

class Comment < ActiveRecord::Base

  # Associations
  belongs_to :user
  belongs_to :post

  # Law of Demeter
  delegate :first_name, to: :user, prefix: true

  # Validation macros
  validates :content, presence: true
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  user_id    :integer
#  content    :text
#  created_at :datetime
#  updated_at :datetime
#  slug       :string(255)
#  post_date  :datetime
#

class Post < ActiveRecord::Base
  before_create :set_post_date

  extend FriendlyId
  friendly_id :post_date_slug, use: :slugged

  # Associations
  belongs_to :user
  # has_many :categories
  has_many :comments, dependent: :destroy

  # Law of Demeter
  delegate :first_name, to: :user, prefix: true

  # Validation macros
  validates :title, presence: true
  validates :content, presence: true

  private

  def set_post_date
    self.post_date = Time.now
  end

  def post_date_slug
    set_post_date.strftime('%Y-%m-%d') + '-' + title.downcase
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id               :integer          not null, primary key
#  email            :string(255)      not null
#  crypted_password :string(255)      not null
#  salt             :string(255)      not null
#  first_name       :string(255)
#  last_name        :string(255)
#  created_at       :datetime
#  updated_at       :datetime
#

class User < ActiveRecord::Base
  authenticates_with_sorcery!

  # Associations
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  # Validation macros
  validates :email, presence: true,
    uniqueness: { case_sensitive: false },
    format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }

  validates :first_name, presence: true,
    length: { in: 3..20 }

  validates :last_name, presence: true,
    length: { in: 3..20 }

  validates :password, presence: true,
    confirmation: true,
    on: :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  # Preventing current_user to log in again, a before filter
  def require_logout
    redirect_to :back, notice: 'Already logged in!' if current_user
  end

  # Callback method for not authenticated user
  def not_authenticated
    redirect_to root_path, alert: 'Please login to access this page.'
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_login

  # Create comment
  def create
    @user = current_user
    @comment = current_user.comments.build(comment_params)
    if @comment.save
      redirect_to @comment.post, notice: 'Comment created!'
    else
      redirect_to @comment.post, alert: 'Something is not right!'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :update, :show, :destroy]
  before_action :require_login, only: [:new, :create, :edit, :destroy]

  # GET /posts
  def index
    @posts = Post.page(params[:page]).per(5)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit; end

  # GET /posts/1
  def show
    @comment = Comment.new
    @comment.post = @post
  end

  # POST /posts/1
  def create
    # @user = current_user
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to @post, notice: 'Post created!'
    else
      render 'new'
    end
  end

  # PUT /posts/1
  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post updated!'
    else
      render 'edit'
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
    redirect_to root_path, notice: 'Post deleted!'
  end

  private

  # Callback for @post, befor_action method
  def set_post
    @post = Post.friendly.find(params[:id])
  end

  # Strong params
  def post_params
    post_attr = [:title, :content]
    params.require(:post).permit(*post_attr)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :require_logout, only: [:new, :create]

  # GET /sessions/new
  def new
    @user = User.new
  end

  # POST /sessions
  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_back_or_to root_path, notice: 'Logged in!'
    else
      redirect_to root_path, alert: 'Invalid email or password. Please check again.'
    end
  end

  # DELETE /sessions
  def destroy
    logout
    redirect_to root_path, notice: 'Logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :destroy]
  before_filter :require_logout, only: [:new, :create]

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1/edit
  def edit
    @user = current_user
  end

  # GET /users/1
  def show; end

  # POST /users
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, notice: 'Check your email for account activation.'
    else
      render 'new'
    end
  end

  # PUT /users/1
  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to @user, notice: 'Profile has been updated!'
    else
      render 'edit'
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to root_path, notice: 'Account deleted!'
  end

  private

  # Callback for @user, before_action method
  def set_user
    @user = User.find(params[:id])
  end

  # Strong params
  def user_params
    user_attr = [:email, :password, :password_confirmation, :first_name, :last_name]
    params.require(:user).permit(*user_attr)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Pygmentize
  class HTMLwithPygments < Redcarpet::Render::HTML
    def block_code(code, language)
      Pygments.highlight(code, lexer: language)
    end
  end

  # Render post content with markdown
  def markdown(text)
    renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
    options = {
      autolink: true,
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true
    }
    find_and_preserve(Redcarpet::Markdown.new(renderer, options).render(text).html_safe)
  end

  # Excerpt first paragraph
  def teaser(post)
    # TODO excerpt first post content paragraph
  end
end

app/views/comments/_comment.html.haml
.panel
  %h5 #{comment.user_first_name}
  %span.date #{time_ago_in_words(comment.created_at)} ago
  %br
  = markdown comment.content

app/views/comments/_form.html.haml
%h5 Add Comment
= simple_form_for @comment do |f|
  = f.input :post_id, as: :hidden
  = f.input :content, label: false, input_html: { rows: 4 }, placeholder: 'Your comment...'
  = f.button :submit, 'Submit', class: 'button tiny'

app/views/layouts/_footer.html.haml
.large-12.columns
  %hr
  .large-6.columns
    %p &copy; 2014 &mdash; Go Blog
  .large-6.columns
    %p.right
      Made with
      %a{href: "#"} Foundation
      and
      %a{href: "#"} Ruby on Rails

app/views/layouts/_header.html.haml
.row
  .large-12.columns
    %h1
      = link_to 'Go Blog', root_path
      %small Go blogging in Rails!
    %hr

app/views/layouts/_message.html.haml
- flash.each do |name, msg|
  %div{class: "alert-box #{name.to_s == 'notice' ? 'notice' : 'alert'}", "data-alert" => ""}
    = content_tag :div, msg
    %a.close{href: ""} &times;

app/views/layouts/_sidebar.html.haml
%h5 Categories
%ul.side-nav
  %li= link_to 'News', '#'
  %li= link_to 'Code', '#'
  %li= link_to 'Weasels', '#'
%hr
%h5 Meta
%ul.side-nav
  - if current_user
    %li= link_to 'New Post', new_post_path
    %li= link_to 'Logout', logout_path
  - else
    %li
      %a{"data-reveal-id" => "loginModal", :href => "#"} Login
    %li= link_to 'Register', register_path


#loginModal.reveal-modal.small{"data-reveal" => ""}
  %h2 Login
  = render 'sessions/form'

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) + " — Go Blog" : "Go Blog"
    = stylesheet_link_tag    "application"
    = javascript_include_tag "vendor/modernizr"
    = csrf_meta_tags
  %body
    .row
      .large-12.columns
        %h1
          = link_to 'Go Blogging', root_path
          %small Go blogging in Rails!
        %hr
    .row
      .large-9.columns
        = render 'layouts/message'
        = yield
      %aside.large-3.columns
        = render 'layouts/sidebar'
    .row
      = render 'layouts/footer'
    = javascript_include_tag "application"

app/views/posts/_form.html.haml
= simple_form_for @post do |f|
  = f.input :title
  = f.input :content, input_html: { rows: 10 }, placeholder: 'Markdown syntax...'
  = f.button :submit, class: 'button tiny'

app/views/posts/edit.html.haml
- provide :title, "Editing #{@post.title}"
.row
  %h3 Edit Post
  .large-9.columns
    = render 'form'
%p= link_to 'Delete', post_path, method: :delete, data: { confirm: 'Are you sure?' }

app/views/posts/index.html.haml
- provide :title, 'Home'
- @posts.order(created_at: :desc).each do |post|
  %article
    %h3= link_to post.title, post
    %h6 Written by #{post.user_first_name} on #{post.created_at.to_formatted_s(:short)}
    = markdown post.content
    %br
= paginate @posts

app/views/posts/new.html.haml
.row
  %h3 New Post
  .large-9.columns
    = render 'form'

app/views/posts/show.html.haml
- provide :title, @post.title
%article
  %h3= @post.title
  %h6 Written by #{@post.user_first_name} on #{@post.created_at.to_formatted_s(:short)}
  = markdown @post.content
  - if current_user
    %p= link_to 'Edit', edit_post_path
  %br
  .row
  .comment
    - if logged_in?
      .row
        .large-9.columns
          = render 'comments/form'
    - else
      .row
        .large-9.columns
          %p Please login to post comment.
    .row
      .large-9.columns
        - if @post.comments.any?
          %h5 Comments
          = render partial: 'comments/comment', collection: @post.comments
        - else
          %p No comments on this post.

app/views/users/_form.html.haml
= simple_form_for @user do |f|
  = f.input :first_name
  = f.input :last_name
  - unless @user.persisted?
    = f.input :email
    = f.input :password
    = f.input :password_confirmation, label: 'Confirmation'
  = f.button :submit, 'Register', class: 'button tiny'

app/views/users/edit.html.haml
.row
  %h3 Edit Profile
  %p Edit your profile information
  .large-6.colums
    = render 'form'

app/views/users/new.html.haml
.row
  %h3 Register
  %p Please fill the information given below.
  .large-6.colums
    = render 'form'

app/views/users/show.html.haml
.row
  .large-6.colums
    %h3 #{@user.first_name}